### ISSUE TITLE
Set up a Tests project

### ISSUE THREAD

**Issue by avodovnik** [avodovnik/qsec-time-service#5]
We need a Tests project, using the `dotnet core` tool again.

**Comment by Jvanderholst** [comment]
I will work on this one

**Comment by Jvanderholst** [comment]
Created pull request

**Comment by Jvanderholst** [comment]
Working on rename

**Comment by avodovnik** [comment]
@Jvanderholst has implemented this in PR #8, so I'm closing this. Will be released with `version-1`
